spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: 1111
  jpa:
    show-sql: true
    open-in-view: false

sbp-limits: 10000.00

integration:
  payments:
    url: 'localhost:8080'
    connect-timeout: 15
    read-timeout: 15